name: GolangCI-Lint

on:
  push:
    paths:
      - go.mod
      - '**.go'
      - .github/workflows/golangci-lint.yml
      - .golangci.yml
  pull_request:
    paths:
      - go.mod
      - '**.go'
      - .github/workflows/golangci-lint.yml
      - .golangci.yml

permissions:
  contents: read
  packages: read

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      GOPRIVATE: github.com/hop-proto/*
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure git for private modules
        run: git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Deps
        run: go get ./...
      - name: Build
        run: go build ./...
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          args: --config=.golangci.yml
